// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF1bikm5BUyHwoCOBIAIpQIC6Wcm9d-xg',
    appId: '1:639078959004:web:c5fde649518a60b6abea59',
    messagingSenderId: '639078959004',
    projectId: 'project-new-b796c',
    authDomain: 'project-new-b796c.firebaseapp.com',
    storageBucket: 'project-new-b796c.firebasestorage.app',
    measurementId: 'G-ZNFK1CFED4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvB6WJPFl5xEFK8YYQkhLp61WORDJ_Rs0',
    appId: '1:639078959004:android:0455e4083b32d29eabea59',
    messagingSenderId: '639078959004',
    projectId: 'project-new-b796c',
    storageBucket: 'project-new-b796c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF1bikm5BUyHwoCOBIAIpQIC6Wcm9d-xg',
    appId: '1:639078959004:web:2426341796df2c2cabea59',
    messagingSenderId: '639078959004',
    projectId: 'project-new-b796c',
    authDomain: 'project-new-b796c.firebaseapp.com',
    storageBucket: 'project-new-b796c.firebasestorage.app',
    measurementId: 'G-X2QEW373W4',
  );
}
